import dotenv from "dotenv";
import connectDB from "../config/db.js";
import Recipe from "../models/Recipe.js";

dotenv.config();

// A curated set of recipes spanning all meal types, common diet tags,
// and goal tags — enough to make the suggestion + grocery-list features
// feel real without needing an external recipe API.
const recipes = [
  {
    name: "Greek Yogurt Berry Bowl",
    description: "A protein-packed breakfast bowl with fresh berries and honey.",
    mealType: "breakfast",
    tags: ["vegetarian", "gluten_free"],
    goalTags: ["lose_weight", "maintain_weight", "build_muscle"],
    prepTimeMinutes: 5,
    servings: 1,
    caloriesPerServing: 290,
    proteinPerServing: 24,
    carbsPerServing: 38,
    fatPerServing: 5,
    ingredients: [
      { name: "Greek yogurt", amount: 200, unit: "g" },
      { name: "Mixed berries", amount: 100, unit: "g" },
      { name: "Honey", amount: 1, unit: "tbsp" },
      { name: "Granola", amount: 20, unit: "g" },
    ],
    instructions: [
      "Spoon the Greek yogurt into a bowl.",
      "Top with mixed berries and granola.",
      "Drizzle honey over the top and serve.",
    ],
  },
  {
    name: "Veggie & Egg Scramble",
    description: "A quick savory scramble loaded with vegetables.",
    mealType: "breakfast",
    tags: ["vegetarian", "gluten_free"],
    goalTags: ["build_muscle", "maintain_weight"],
    prepTimeMinutes: 10,
    servings: 1,
    caloriesPerServing: 320,
    proteinPerServing: 22,
    carbsPerServing: 10,
    fatPerServing: 21,
    ingredients: [
      { name: "Eggs", amount: 3, unit: "piece" },
      { name: "Spinach", amount: 40, unit: "g" },
      { name: "Tomato", amount: 60, unit: "g" },
      { name: "Olive oil", amount: 1, unit: "tsp" },
    ],
    instructions: [
      "Heat olive oil in a pan over medium heat.",
      "Add spinach and tomato, sauté for 2 minutes.",
      "Whisk the eggs and pour into the pan.",
      "Scramble until just set, then serve.",
    ],
  },
  {
    name: "Overnight Oats",
    description: "Make-ahead oats that are ready when you wake up.",
    mealType: "breakfast",
    tags: ["vegan", "vegetarian"],
    goalTags: ["gain_weight", "maintain_weight"],
    prepTimeMinutes: 5,
    servings: 1,
    caloriesPerServing: 350,
    proteinPerServing: 12,
    carbsPerServing: 55,
    fatPerServing: 9,
    ingredients: [
      { name: "Oats (dry)", amount: 60, unit: "g" },
      { name: "Almond milk", amount: 200, unit: "ml" },
      { name: "Banana", amount: 1, unit: "piece" },
      { name: "Peanut butter", amount: 1, unit: "tbsp" },
    ],
    instructions: [
      "Combine oats and almond milk in a jar.",
      "Slice the banana and mix in half, saving the rest for topping.",
      "Refrigerate overnight.",
      "Top with peanut butter and remaining banana before eating.",
    ],
  },
  {
    name: "Grilled Chicken & Quinoa Bowl",
    description: "A balanced, high-protein lunch bowl.",
    mealType: "lunch",
    tags: ["gluten_free"],
    goalTags: ["build_muscle", "lose_weight"],
    prepTimeMinutes: 25,
    servings: 1,
    caloriesPerServing: 480,
    proteinPerServing: 42,
    carbsPerServing: 45,
    fatPerServing: 13,
    ingredients: [
      { name: "Chicken breast (cooked)", amount: 150, unit: "g" },
      { name: "Quinoa (cooked)", amount: 150, unit: "g" },
      { name: "Broccoli", amount: 100, unit: "g" },
      { name: "Olive oil", amount: 1, unit: "tbsp" },
    ],
    instructions: [
      "Grill or pan-sear the chicken breast until cooked through.",
      "Steam the broccoli until tender-crisp.",
      "Combine quinoa, chicken, and broccoli in a bowl.",
      "Drizzle with olive oil and season to taste.",
    ],
  },
  {
    name: "Chickpea & Spinach Salad",
    description: "A light, fiber-rich vegan lunch.",
    mealType: "lunch",
    tags: ["vegan", "vegetarian", "gluten_free"],
    goalTags: ["lose_weight", "maintain_weight"],
    prepTimeMinutes: 10,
    servings: 1,
    caloriesPerServing: 340,
    proteinPerServing: 14,
    carbsPerServing: 40,
    fatPerServing: 14,
    ingredients: [
      { name: "Chickpeas (cooked)", amount: 150, unit: "g" },
      { name: "Spinach", amount: 60, unit: "g" },
      { name: "Tomato", amount: 60, unit: "g" },
      { name: "Olive oil", amount: 1, unit: "tbsp" },
      { name: "Lemon juice", amount: 1, unit: "tbsp" },
    ],
    instructions: [
      "Toss chickpeas, spinach, and tomato in a large bowl.",
      "Whisk olive oil and lemon juice together for the dressing.",
      "Pour dressing over the salad and toss to combine.",
    ],
  },
  {
    name: "Turkey & Avocado Wrap",
    description: "A quick, portable lunch with healthy fats.",
    mealType: "lunch",
    tags: [],
    goalTags: ["maintain_weight", "gain_weight"],
    prepTimeMinutes: 10,
    servings: 1,
    caloriesPerServing: 420,
    proteinPerServing: 28,
    carbsPerServing: 35,
    fatPerServing: 18,
    ingredients: [
      { name: "Whole wheat tortilla", amount: 1, unit: "piece" },
      { name: "Turkey breast (sliced)", amount: 100, unit: "g" },
      { name: "Avocado", amount: 0.5, unit: "piece" },
      { name: "Spinach", amount: 20, unit: "g" },
    ],
    instructions: [
      "Lay the tortilla flat and layer turkey, avocado, and spinach.",
      "Roll tightly, slice in half, and serve.",
    ],
  },
  {
    name: "Baked Salmon with Sweet Potato",
    description: "An omega-3 rich dinner with roasted sweet potato.",
    mealType: "dinner",
    tags: ["gluten_free"],
    goalTags: ["build_muscle", "maintain_weight"],
    prepTimeMinutes: 35,
    servings: 1,
    caloriesPerServing: 520,
    proteinPerServing: 36,
    carbsPerServing: 40,
    fatPerServing: 22,
    ingredients: [
      { name: "Salmon fillet", amount: 150, unit: "g" },
      { name: "Sweet potato", amount: 200, unit: "g" },
      { name: "Olive oil", amount: 1, unit: "tbsp" },
      { name: "Asparagus", amount: 80, unit: "g" },
    ],
    instructions: [
      "Preheat oven to 200°C (400°F).",
      "Toss sweet potato and asparagus with olive oil, spread on a tray.",
      "Place salmon on the same tray and season.",
      "Bake for 20–25 minutes until salmon flakes easily.",
    ],
  },
  {
    name: "Tofu Stir-Fry",
    description: "A colorful vegan stir-fry with crispy tofu.",
    mealType: "dinner",
    tags: ["vegan", "vegetarian"],
    goalTags: ["lose_weight", "maintain_weight"],
    prepTimeMinutes: 25,
    servings: 1,
    caloriesPerServing: 390,
    proteinPerServing: 22,
    carbsPerServing: 38,
    fatPerServing: 16,
    ingredients: [
      { name: "Tofu", amount: 150, unit: "g" },
      { name: "Broccoli", amount: 100, unit: "g" },
      { name: "Carrot", amount: 60, unit: "g" },
      { name: "Soy sauce", amount: 1, unit: "tbsp" },
      { name: "Brown rice (cooked)", amount: 150, unit: "g" },
    ],
    instructions: [
      "Pan-fry cubed tofu until golden on all sides.",
      "Add broccoli and carrot, stir-fry for 4–5 minutes.",
      "Add soy sauce and toss to coat.",
      "Serve over brown rice.",
    ],
  },
  {
    name: "Lean Beef & Roti Curry",
    description: "A hearty, high-protein dinner with a homestyle feel.",
    mealType: "dinner",
    tags: [],
    goalTags: ["gain_weight", "build_muscle"],
    prepTimeMinutes: 40,
    servings: 1,
    caloriesPerServing: 560,
    proteinPerServing: 38,
    carbsPerServing: 48,
    fatPerServing: 22,
    ingredients: [
      { name: "Lean beef", amount: 150, unit: "g" },
      { name: "Roti / Chapati", amount: 2, unit: "piece" },
      { name: "Tomato", amount: 80, unit: "g" },
      { name: "Onion", amount: 50, unit: "g" },
    ],
    instructions: [
      "Sauté onion until soft, then add tomato and cook down into a base.",
      "Add beef and simmer until cooked through and tender.",
      "Serve hot with roti.",
    ],
  },
  {
    name: "Apple & Almond Butter",
    description: "A simple 2-ingredient snack with fiber and healthy fat.",
    mealType: "snack",
    tags: ["vegan", "vegetarian", "gluten_free"],
    goalTags: ["lose_weight", "maintain_weight"],
    prepTimeMinutes: 3,
    servings: 1,
    caloriesPerServing: 200,
    proteinPerServing: 5,
    carbsPerServing: 22,
    fatPerServing: 11,
    ingredients: [
      { name: "Apple", amount: 1, unit: "piece" },
      { name: "Almond butter", amount: 1, unit: "tbsp" },
    ],
    instructions: ["Slice the apple.", "Serve with almond butter for dipping."],
  },
  {
    name: "Protein Smoothie",
    description: "A fast, high-protein snack or post-workout refuel.",
    mealType: "snack",
    tags: ["vegetarian", "gluten_free"],
    goalTags: ["build_muscle", "gain_weight"],
    prepTimeMinutes: 5,
    servings: 1,
    caloriesPerServing: 280,
    proteinPerServing: 25,
    carbsPerServing: 30,
    fatPerServing: 6,
    ingredients: [
      { name: "Whey protein powder", amount: 30, unit: "g" },
      { name: "Banana", amount: 1, unit: "piece" },
      { name: "Milk", amount: 250, unit: "ml" },
    ],
    instructions: ["Add all ingredients to a blender.", "Blend until smooth and serve immediately."],
  },
  {
    name: "Cottage Cheese & Pineapple",
    description: "A light, high-protein snack with natural sweetness.",
    mealType: "snack",
    tags: ["vegetarian", "gluten_free"],
    goalTags: ["lose_weight", "maintain_weight"],
    prepTimeMinutes: 3,
    servings: 1,
    caloriesPerServing: 180,
    proteinPerServing: 18,
    carbsPerServing: 18,
    fatPerServing: 3,
    ingredients: [
      { name: "Cottage cheese", amount: 150, unit: "g" },
      { name: "Pineapple chunks", amount: 80, unit: "g" },
    ],
    instructions: ["Combine cottage cheese and pineapple in a bowl and serve chilled."],
  },
];

const run = async () => {
  await connectDB();
  await Recipe.deleteMany({});
  await Recipe.insertMany(recipes);
  console.log(`Seeded ${recipes.length} recipes`);
  process.exit(0);
};

run().catch((err) => {
  console.error("Failed to seed recipes:", err);
  process.exit(1);
});
